### ISSUE TITLE
Retrospective

### ISSUE THREAD

**Issue by nicksarafa** [wix-incubator/mjml-react-example#2]
Hey there!

Are you guys using this library internally for rendering your react/mjml based emails? Is the purpose of this library to output the standard HTML, much like the regular MJML library? I'm interested in outputting static HTML using the MJML library, and react + styled components to share styles between our react web, react-native, and email templates.

Great library! Thanks for creating it!

**Comment by kranux** [comment]
Hi,

yes, we use this library to render our emails on server side.

Output of this library is identical to original Mjml as it's just React wrapper.

Let me know if you have more questions! :)
